options:
  lineNumbers: true
  imagePrefix: liangyuanzheng.com-
  askImageFilename: false
  spellcheck: true
  imagePath: images
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true
