# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/



# Site
title: 七点一刻
subtitle:  
description: day day up
author: LeungGeorge
language: zh-Hans
timezone: Asia/Shanghai
avatar: https://avatars2.githubusercontent.com/u/9783818?v=3&u=e2bb1f397cfd1d21252d25563057694fe8704850&s=140  # 头像的URL

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://leunggeorge.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - search.html

# Writing
new_post_name: :year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #显示草稿
post_asset_folder: true #是否启动资源文件夹
relative_link: false #把链接改为与根目录的相对位址
future: true
highlight: #代码块的设置
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag 分类 & 标签
default_category: uncategorized #默认分类
category_map: #分类别名
tag_map:      #标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: yilia
# theme: pacman
# theme: jacman
# theme: hexo-theme-next
# theme: uno
# theme: concise
# theme: hexo-theme-freemind
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/LeungGeorge/LeungGeorge.github.io.git
  branch: master

algolia:
  applicationID: 'FWXTLLN24O'
  apiKey: '9fe78ed368d4c017f33c16a170ce10a0'
  adminApiKey: '8497682cec675ee57e29c86c41956994'
  indexName: 'dev_jobbymsblog'
  chunkSize: 5000

#search: true
search: 
  path: search.xml
  field: post
  format: html
  limit: 10000

#RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

# 为首页和归档页面设置不同的文章篇数
index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  item_text: true
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长
  totalcount: true       # 网站 字数统计
  separated_meta: true
